### ISSUE TITLE
onError Callback: 2011 -> Join session error, invalid parameter.

### ISSUE THREAD

**Issue by jacabodam** [zoom/videosdk-ui-toolkit-ios#2] opened 2024-05-31 12:25 UTC
It seems that upon running the example, an error occurred with the following message: "onError Callback: 2011 -> Join session error, invalid parameter." Despite not making any modifications, you encountered this issue. What are the potential causes for this?

**Comment by BoonJunTan** [comment] 2024-08-21 06:32
Hi @jacabodam,

Sorry for the delayed response. The error is usually caused by having mismatched information in the JWT tokens and session name. You can make use of our online JWT generation tool [here](https://developers.zoom.us/docs/video-sdk/auth/) if it's more convenient.

Are you currently still experiencing this issue?

**Comment by BoonJunTan** [comment] 2024-09-21 01:38
@jacabodam I will close this issue for now. Do let me know if you still experience any issue.

**Closed as completed by BoonJunTan** 2024-09-21 01:38 UTC
